name: Primeira Pipeline

on:
    push:
        branches: [main]

jobs:
    teste:
        strategy:
         matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{matrix.os}}

        steps:
            - name: Baixar Código do Repositório
              uses: actions/checkout@v4
            
            - name: Configurar Python
              uses: actions/setup-python@v5
            
    deploy:
        needs: teste
        runs-on: ubuntu-latest
    
        steps:
            - run: echo "Deploy Realizado"